add some html&css
maxdemo1/project_First_Flight pull request #3
Opened 2023-10-11 20:26 UTC by YuriyDobryanskiy

2023-10-11 20:27 UTC, YuriyDobryanskiy commented
& edit base css

2023-10-11 21:02 UTC, maxdemo1 requested changes
Класно вийшло, є кілька зауважень, розписав в коментарях

2023-10-11 21:02 UTC, maxdemo1 commented on src/css/sign_up.css
якщо робиш відступи між секціями падінгами, роби їх в половину менше тобто на макеті 80px, значить у тебе 40px через те що падінги не схлопуються як маржини

2023-10-11 21:02 UTC, maxdemo1 commented on src/css/sign_up.css
властивості transition домовлялися робити як в дз, виправ будь ласка

2023-10-11 21:11 UTC, YuriyDobryanskiy commented on src/css/base.css
там якраз контейнер 1240 + 100 падінги

2023-10-11 21:13 UTC, YuriyDobryanskiy commented on src/css/sign_up.css
> для класу .sign-up__text повинно бути обмеження по ширині

 я у sign-up__block-form (у батька) обмежую ширину

2023-10-11 21:15 UTC, YuriyDobryanskiy commented on src/css/sign_up.css
> placeholder в формах потрібно задати непрозорими кольорами

там є opacity: .7;

2023-10-11 21:16 UTC, YuriyDobryanskiy commented on src/css/sign_up.css
> Мій провтик, прозорими, але не 0.2 а 0.7

.2 у рамки

2023-10-11 21:37 UTC, YuriyDobryanskiy commented on src/css/sign_up.css
> селектор .sign-up__input-container:not(:last-child) не працює, поки не розумію в чому проблема, може на свіжу голову дойде)

підправлю

2023-10-11 21:39 UTC, YuriyDobryanskiy commented on src/css/sign_up.css
> .subtext властивість color неправильна, там повина бути прозорість

так і є rgba(255, 255, 255, 0.5);

2023-10-11 21:41 UTC, YuriyDobryanskiy commented on src/css/sign_up.css
> якщо робиш відступи між секціями падінгами, роби їх в половину менше тобто на макеті 80px, значить у тебе 40px через те що падінги не схлопуються як маржини

між секціями так і брав 50% загальгого margin

2023-10-11 21:56 UTC, YuriyDobryanskiy commented on src/css/sign_up.css
> transition
така?
transition: background-color 250ms cubic-bezier(0.4, 0, 0.2, 1);

2023-10-12 17:32 UTC, maxdemo1 requested changes

2023-10-12 17:32 UTC, maxdemo1 commented on src/css/base.css
я зрозумів, але давай по іншому, загальна ширина 1440px, а контент всередину втискаємо падінгами, а не робимо відступ маржинами
Тобто 
max-width: 1440px;
padding: 0 20px;

2023-10-12 17:32 UTC, maxdemo1 commented on src/css/base.css
Так як ти зробив теж буде працювати, але в дз у всіх використовувався такий підхід, тому думаю так буде зручніше

2023-10-12 17:32 UTC, maxdemo1 commented on src/css/sign_up.css
> > для класу .sign-up__text повинно бути обмеження по ширині
> 
> я у sign-up__block-form (у батька) обмежую ширину

так, але на макеті у даного блока ще більше обмежена ширина, ніж в батьківського елемента

2023-10-12 18:11 UTC, maxdemo1 approved these changes

2023-10-12 18:15 UTC, merged